# 알고리즘 선택: round_robin | weighted | least_connections
algorithm = "least_connections"

# 백엔드 설정: addr | String, weight | Option<u8>
[[backends]]
addr = "127.0.0.1:8081"
weight = 1  # Option<u8>

[[backends]]
addr = "127.0.0.1:8082"
weight = 1